#Type of punishment after losing all of lives
#EXILE - Prevents player from joining server
#COMMAND - Preconfigured command is executed
#DROP_ITEMS - Drops all player items
#MONEY - Takes some  money
#NONE - Nothing
deathPunishment: EXILE

#=========================================
#======= Exile punishment settings =======
#=========================================

#Should player be banned from server forever
permanentDeath: false

#Death time in hours
deathTime: 2

#Should players be able to resurrect another player
resurrectionEnabled: true

#Amount of lives needed for resurrections
resurrectionCost: 1

#=========================================
#====== Command punishment settings ======
#=========================================

#Command executed after losing all lives
#You can set multiple commands
punishmentCommands:
  - "broadcast %player% just lost all lives!"

#==== Drop items punishment settings ====

#Should items be dropped to world or just inventory be cleared
dropToWorld: true

#=========================================
#======= Money punishment settings =======
#=========================================

#Vault and economy plugin must be installed to use this punishment

#Amount that will be taken from player after losing all livse
moneyToTake: 500.0

#Punishment that will be used if player don't have enough money
notEnoughMoneyPunishment: EXILE

#=========================================
#============ Lives settings =============
#=========================================

#Should players be able to buy additional live for money
buyableLives: true

#Money cost of life
#that sounds weird D:
lifeCost: 500

#Items that will give player lives
#Here diamond will restore 1 life and diamond block 3 lives
eatableItems:
  DIAMOND: 1
  DIAMOND_BLOCK: 3

#Remember to write 'ID' of your item form customItems.yml
eatableCustomItems:
  customHeart: 1

#Starting amount of player lifes
defaultLivesAmount: 3

#Max amount
#If you want to set max lives per permission change 'maxLivesPermissionBased' to true and then
#configure maxLivesPermissions
maxLivesPermissionBased: false
maxLives: 10

#Remember to write from highest to lowest number
#If player won't have any of these permissions standard 'maxLives' value will be used
maxLivesPermissions:
  10: playerlives.maxlives.10
  5: playerlives.maxlives.5
  1: playerlives.maxlives.1

#Allow players to eat items to gain a life
eatingEnabled: true

#Amount of lives resurrected player will have after resurrection
livesAfterPunishment: 1

#=====================================