name: PlayerLives
version: 1.0.2
main: pl.pijok.playerlives.PlayerLives
author: Pijok
softdepend:
  - PlaceholderAPI
commands:
  playerlives:
    usage: /playerlives
    description: Used to modify lives of players or to reload plugin
    aliases: [playerl, lives, plives]
  resurrect:
    usage: /resurrect
    description: Used to resurrect player and give him life